server:
  port: 8040
  servlet:
    context-path: /hero
    encoding:
      force-response: true
  shutdown: immediate
spring:
  application:
    name: hero
  main:
    lazy-initialization: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  datasource:
    url: 'jdbc:postgresql://49.232.165.242:5432/merchant'
    driver-class-name: org.postgresql.Driver
    username: 'postgres'
    password: 'postgres'
    hikari:
      schema: develop
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
logging:
  level:
    root: info

system:
  logo: 'picture/logo.png'
  secret: '123456a?'
  file-path: home/picture
