def GetRemoteServer(ip){
    def remote = [:]
    remote.name = ip
    remote.host = ip
    remote.port = 22
    remote.allowAnyHosts = true
    withCredentials([usernamePassword(credentialsId: ip, passwordVariable: 'password', usernameVariable: 'userName')]) {
        remote.user = "${userName}"
        remote.password = "${password}"
    }
    return remote
}


pipeline {
    agent any
    stages {
        stage("install") {
            steps {
                bat 'cd Website/platform && yarn install && yarn run build'
            }
        }

        stage("upload dist") {
            steps {
                script {
                     server = GetRemoteServer('49.232.165.242')
                     sshCommand remote: server, command: 'mkdir -p /home/resources/platform'
                     sshPut remote: server, from: 'Website/platform/dist', into: '/home/resources/platform'
                }
            }
        }
    }
}
