server:
  port: 8030
  servlet:
    context-path: /platform
    encoding:
      force-response: true
  shutdown: graceful
spring:
  application:
    name: platform
  main:
    lazy-initialization: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  datasource:
    url: 'jdbc:postgresql://<IP>:5432/<DATABASE>'
    driver-class-name: org.postgresql.Driver
    username: '数据库账号'
    password: '数据库密码'
    hikari:
      schema: develop
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-develop.sql

logging:
  file:
    path: log/platform
  level:
    root: info

system:
  logo: 'picture/logo.png'
  secret: 系统密钥
  file-path: home/picture
