server:
  port: 8030
  servlet:
    context-path: /platform
    encoding:
      force-response: true
  shutdown: graceful
spring:
  application:
    name: platform
  main:
    lazy-initialization: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  datasource:
    url: 'jdbc:postgresql://49.232.165.242:5432/merchant'
    driver-class-name: org.postgresql.Driver
    username: 'postgres'
    password: 'postgres'
    hikari:
      schema: master
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-master.sql
logging:
  file:
    path: log/platform
  level:
    root: info

system:
  logo: 'picture/logo.png'
  secret: '123456a?'
  file-path: home/picture
